name: Demo Workflow
run-name: auto
on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Get working directory
        run: pwd
        
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
            cd .github/workflows
            chmod +x ./test.sh
            ./test.sh PR_TITLE=${{ steps.PR.outputs.pr_title }} REPOSITORY_NAME=${{fromJSON(steps.PR.outputs.pr).head.repo.full_name}} DETAILS=${{fromJSON(steps.PR.outputs.pr).body}} DEVELOPER_LOGIN=${{ fromJSON(steps.PR.outputs.pr).user.login}}
