name: Demo Workflow
run-name: auto
on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Get working directory
        run: pwd

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
        
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: python3 main.py --pr_title=${{ steps.PR.outputs.pr_title }} --contributor_login=${{ fromJSON(steps.PR.outputs.pr).user.login}} --merged_at=${{steps.PR.outputs.pr_merged_at}} --repo_name=${{fromJSON(steps.PR.outputs.pr).head.repo.full_name}}"
