name: Demo Workflow
run-name: auto
on:
  push:
    branches:
      - main

      
jobs:
  update_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
            sudo chmod +x .github/workflows/update_notifier.sh
            .github/workflows/update_notifier.sh BOT_API_KEY=${{ secrets.TG_TOKEN }} CHAT_ID=${{ secrets.DD_SUPPORT_TG_CHAT_ID }} PR_TITLE="${{ steps.PR.outputs.pr_title }}" REPOSITORY_NAME="${{fromJSON(steps.PR.outputs.pr).head.repo.full_name}}" DETAILS="${{ steps.PR.outputs.pr_body}}" DEVELOPER_LOGIN="${{ fromJSON(steps.PR.outputs.pr).user.login}}"
