name: Demo Workflow
on:
  merge_group:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"
