name: Demo Workflow
on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR

      - run: echo "Your PR title is ${{ steps.PR.outputs.pr.title }} and its user login is ${{ steps.PR.outputs.pr.user.login}}  and merged_at ${{steps.PR.outputs.pr.merged_at}} and description is ${{steps.PR.outputs.pr.description}}"       
