name: Demo Workflow
on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
        
      - name: Redirect event to file
        run: echo '${{ toJSON(github.event) }}' >> event.json
